[package]
name = "ruvoy-envoy-fiber"
description = "Envoy dynamic module serving Rack applications on a fiber runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "ruvoy_fiber"
crate-type = ["cdylib", "rlib"]

[dependencies]
envoy-proxy-dynamic-modules-rust-sdk.workspace = true
libc.workspace = true
ruvoy.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
