[package]
name = "ruvoy-envoy-sync"
description = "Envoy dynamic module serving Rack applications on a serial runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "ruvoy_sync"
crate-type = ["cdylib", "rlib"]

[dependencies]
envoy-proxy-dynamic-modules-rust-sdk.workspace = true
ruvoy.workspace = true

[lints]
workspace = true
